#!/bin/bash 

# Check if empty 
if [ -z $1 ];then
       echo "No argument, use -h for help." 
       exit 0
fi

# Options
if [ $1 = "-h" ];then
        cat ~/Documents/3.compscience/3.config/Linux/scripts//man/help_page
        exit 0
elif [ $1 = "-l" ];then
        ls ~/Documents/3.compscience/3.config/Linux/scripts//man/
        exit 0
fi


